name: Release

on:
  push:
    branches:
      - main
      - next
      - beta
      - alpha

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Locate Yarn Cache Directory
        id: locate-yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Retrieve Yarn Cache
        id: retrieve-yarn-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.locate-yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Packages
        run: yarn install

      - name: Compile
        run: yarn build

      - name: Upload Compiled Files
        uses: actions/upload-artifact@v2
        with:
          name: compiled-files
          path: dist/

      - name: Test
        run: yarn test --coverage

      - name: Report coverage
        uses: coverallsapp/github-action@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
